### ISSUE TITLE
Re-ordering lessons

### ISSUE THREAD

**Issue by tmb41** [learn-co-curriculum/each-vs-collect-readme#3]
Hey,

Just a suggestion, but it seems like this lesson on MAP and COLLECT may be better if it came before the Array exercise (Badges and Schedules) where you need to use MAP to pass the lesson (need to adjust array as you iterate through it). I didn't yet know about MAP and luckily someone else was able to help answer my question and I passed the original lesson.

Apologies if I made a mistake on my end and didn't go through the lessons in proper order.

Thanks

**Comment by AnnJohn** [comment]
hi @tmb41, thanks for the suggestion. The reason why we put this after the Badges and Schedule lesson is that we want students to google around for the answer in that lesson (it's what we tell students to do in one of the hints.) Googling is actually a huge part of working as a developer, and it's also important too to get an understanding of how to search Ruby documentation. 

But thanks again for the suggestion!
