### ISSUE TITLE
order of lessons

### ISSUE THREAD

**Issue by tostonar** [learn-co-curriculum/each-vs-collect-readme#8]
I feel like the "Collect and Return Values" lesson should have come before the "Square Array" lab. It would have been more helpful that way, rather than me searching across the internet for possible answers. I know that learning to google properly is also a skill that developers should build, I feel like I shouldn't have to look at the curriculum from other programs to get the right information because then I feel like the curriculum here at Flatiron School Online isn't complete. Perhaps if people could post on a forum, for each lab, what resources they felt were useful, that could help others.

**Comment by sgharms** [comment]
Closing folding into #10
