### ISSUE TITLE
Problem with the curriculum

### ISSUE THREAD

**Issue by DoriansGrave** [learn-co-curriculum/each-vs-collect-readme#9]
Why does the "Collect and Return Values" unit come after these two labs (see screenshot), both of which require the use of operators (specifically the .map operator) that are completely unreferenced and undefined until this lesson? This is not remotely the only example of this kind of disorganization in the curriculum. At several points I have been forced to look into the solution to figure out what isn't working with my code, only to find that I'm missing elements that I haven't been taught yet; or have been likewise confused by outdated videos that use different software and file organization, taught by an instructor who spends minutes tediously articulating something that is empirically obvious, but presenting material that gets introduced as a necessary component and then used without explanation until long after it's been in his rotation (this is mostly a problem during the front-end modules). Seeing as how this course is paid on a time-use basis, mistakes that add to the amount of time I have to spend on anything are unacceptable. Please correct these mistakes or re-evaluate this strategy.

<img width="1440" alt="screen shot 2017-05-26 at 11 46 35 am" src="https://cloud.githubusercontent.com/assets/26909418/26504261/776d63c4-4209-11e7-8011-d4d1da3427a0.png">

**Comment by sgharms** [comment]
Folding into a master issue
